//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICANT_REFEREE_RESPONSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APPLICANT_REFEREE_RESPONSE()
        {
            this.APPLICANT_REFEREE_GRADING_RESPONSE = new HashSet<APPLICANT_REFEREE_GRADING_RESPONSE>();
        }
    
        public long Referee_Response_Id { get; set; }
        public long Applicant_Referee_Id { get; set; }
        public decimal DurationKnownApplicant { get; set; }
        public string Remark { get; set; }
        public bool CanAcceptApplicant { get; set; }
        public int Overall_Rating { get; set; }
        public string Relevant_Information { get; set; }
        public bool Disclose_Response { get; set; }
        public string Full_Name { get; set; }
        public string Signature_Url { get; set; }
        public System.DateTime Date_Of_Response { get; set; }
    
        public virtual APPLICANT_REFEREE APPLICANT_REFEREE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPLICANT_REFEREE_GRADING_RESPONSE> APPLICANT_REFEREE_GRADING_RESPONSE { get; set; }
        public virtual REFEREE_GRADING_SYSTEM REFEREE_GRADING_SYSTEM { get; set; }
    }
}
