//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICANT_JAMB_DETAIL_AUDIT
    {
        public long Applicant_Jamb_Audit_Id { get; set; }
        public long Person_Id { get; set; }
        public string Applicant_Jamb_Registration_Number { get; set; }
        public Nullable<short> Applicant_Jamb_Score { get; set; }
        public Nullable<int> Institution_Choice_Id { get; set; }
        public Nullable<long> Application_Form_Id { get; set; }
        public Nullable<int> Subject1 { get; set; }
        public Nullable<int> Subject2 { get; set; }
        public Nullable<int> Subject3 { get; set; }
        public Nullable<int> Subject4 { get; set; }
        public long User_Id { get; set; }
        public string Operation { get; set; }
        public string Action { get; set; }
        public System.DateTime Time { get; set; }
        public string Client { get; set; }
    }
}
