//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICANT_REFEREE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APPLICANT_REFEREE()
        {
            this.APPLICANT_REFEREE_RESPONSE = new HashSet<APPLICANT_REFEREE_RESPONSE>();
        }
    
        public long Applicant_Referee_Id { get; set; }
        public string Name { get; set; }
        public string Rank { get; set; }
        public string Department { get; set; }
        public string Institution { get; set; }
        public long Application_Form_Id { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
    
        public virtual APPLICATION_FORM APPLICATION_FORM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPLICANT_REFEREE_RESPONSE> APPLICANT_REFEREE_RESPONSE { get; set; }
    }
}
