//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICANT_REFEREE_GRADING_RESPONSE
    {
        public long Id { get; set; }
        public long Applicant_Response_Id { get; set; }
        public int Referee_Grading_Category_Id { get; set; }
        public int Referee_Grading_System_Id { get; set; }
    
        public virtual APPLICANT_REFEREE_RESPONSE APPLICANT_REFEREE_RESPONSE { get; set; }
        public virtual REFEREE_GRADING_CATEGORY REFEREE_GRADING_CATEGORY { get; set; }
        public virtual REFEREE_GRADING_SYSTEM REFEREE_GRADING_SYSTEM { get; set; }
    }
}
