//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE_ALLOCATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COURSE_ALLOCATION()
        {
            this.E_CHAT_TOPIC = new HashSet<E_CHAT_TOPIC>();
            this.E_CONTENT_TYPE = new HashSet<E_CONTENT_TYPE>();
            this.E_ASSIGNMENT = new HashSet<E_ASSIGNMENT>();
        }
    
        public long Course_Allocation_Id { get; set; }
        public long User_Id { get; set; }
        public long Course_Id { get; set; }
        public int Department_Id { get; set; }
        public int Level_Id { get; set; }
        public int Session_Id { get; set; }
        public Nullable<int> Semester_Id { get; set; }
        public int Programme_Id { get; set; }
        public Nullable<bool> Is_HOD { get; set; }
        public Nullable<bool> Is_Dean { get; set; }
        public Nullable<int> HOD_Department_Id { get; set; }
        public Nullable<int> DepartmentOption_Id { get; set; }
    
        public virtual COURSE COURSE { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual DEPARTMENT_OPTION DEPARTMENT_OPTION { get; set; }
        public virtual DEPARTMENT DEPARTMENT1 { get; set; }
        public virtual LEVEL LEVEL { get; set; }
        public virtual PROGRAMME PROGRAMME { get; set; }
        public virtual SEMESTER SEMESTER { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<E_CHAT_TOPIC> E_CHAT_TOPIC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<E_CONTENT_TYPE> E_CONTENT_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<E_ASSIGNMENT> E_ASSIGNMENT { get; set; }
    }
}
