//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEGREE_AWARDS_BY_PROGRAMME_DEPARTMENT
    {
        public long Id { get; set; }
        public int Department_Id { get; set; }
        public int Programme_Id { get; set; }
        public string Degree_Name { get; set; }
        public Nullable<int> Duration { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual PROGRAMME PROGRAMME { get; set; }
    }
}
