//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERY_SERVICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DELIVERY_SERVICE()
        {
            this.DELIVERY_SERVICE_ZONE = new HashSet<DELIVERY_SERVICE_ZONE>();
        }
    
        public int Delivery_Service_Id { get; set; }
        public string Name { get; set; }
        public string Delivery_Service_Account { get; set; }
        public string Bank_Code { get; set; }
        public string Description { get; set; }
        public bool Activated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERY_SERVICE_ZONE> DELIVERY_SERVICE_ZONE { get; set; }
    }
}
