//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUPLICATE_ADMISSION_LIST
    {
        public long Application_Form_Id { get; set; }
        public string Applicant_Jamb_Registration_Number { get; set; }
        public long Person_Id { get; set; }
    }
}
