//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_CONTENT_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public E_CONTENT_TYPE()
        {
            this.E_COURSE_CONTENT = new HashSet<E_COURSE_CONTENT>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public long Course_Allocation_Id { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual COURSE_ALLOCATION COURSE_ALLOCATION { get; set; }
        public virtual E_CONTENT_TYPE E_CONTENT_TYPE1 { get; set; }
        public virtual E_CONTENT_TYPE E_CONTENT_TYPE2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<E_COURSE_CONTENT> E_COURSE_CONTENT { get; set; }
    }
}
