//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE_DETAIL
    {
        public long Staff_Id { get; set; }
        public Nullable<int> Year_Of_Employment { get; set; }
        public string Staff_Number { get; set; }
        public Nullable<int> Designation_Id { get; set; }
        public Nullable<int> Grade_Level_Id { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public Nullable<int> Unit_Id { get; set; }
        public Nullable<System.DateTime> Date_Of_Previous_Apointment { get; set; }
        public Nullable<System.DateTime> Date_Of_Present_Appointment { get; set; }
        public Nullable<System.DateTime> Date_Of_Retirement { get; set; }
        public string Employment_Location { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual DESIGNATION DESIGNATION { get; set; }
        public virtual GRADE_LEVEL GRADE_LEVEL { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
