//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GST_SCAN
    {
        public long Id { get; set; }
        public string Matric_Number { get; set; }
        public string Student_Name { get; set; }
        public string CourseCode { get; set; }
        public string Programme { get; set; }
        public string Semester { get; set; }
        public string Session { get; set; }
        public decimal Score { get; set; }
        public string Shaded { get; set; }
        public int Department_Id { get; set; }
        public int Programme_Id { get; set; }
        public Nullable<long> Course_Id { get; set; }
        public Nullable<long> Student_Id { get; set; }
    
        public virtual COURSE COURSE { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual PROGRAMME PROGRAMME1 { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
