//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIGRATION_APPLICANTS
    {
        public int SNO { get; set; }
        public string JAMB_REG_NO { get; set; }
        public string NAMES { get; set; }
        public string STATE { get; set; }
        public string LGA { get; set; }
        public string FIRST_CHOICE { get; set; }
        public Nullable<double> SCORE { get; set; }
        public string QUALIFICATION_1 { get; set; }
        public string QUALIFICATION_2 { get; set; }
        public string DEPARTMENT { get; set; }
    }
}
