//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIGRATION_REGISTERED_COURSES
    {
        public long SN { get; set; }
        public string Matric_No { get; set; }
        public string Fullname { get; set; }
        public string Department { get; set; }
        public string Level { get; set; }
        public string Semester { get; set; }
        public string Session { get; set; }
        public string Course_Code { get; set; }
        public string ExamScore { get; set; }
        public string Course_Unit { get; set; }
    }
}
