//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIGRATION_ETRANZACT
    {
        public double SN { get; set; }
        public string Matric_No_ { get; set; }
        public string AMOUNT { get; set; }
        public string FULLNAME { get; set; }
        public string CONFIRMATION_CODE { get; set; }
        public string SESSION { get; set; }
        public string PAYMENT_DETAILS { get; set; }
        public string PROGRAMME { get; set; }
        public string LEVEL { get; set; }
        public string SEMESTER { get; set; }
    }
}
