//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIGRATION_BIODATA
    {
        public long SN { get; set; }
        public string STUDENTNAME { get; set; }
        public string DOB { get; set; }
        public string SEX { get; set; }
        public string REG_NO { get; set; }
        public string JAMB_REG_NO { get; set; }
        public string DEPARTMENT { get; set; }
        public string FACULTY { get; set; }
        public string CONTACT_ADDRESS { get; set; }
        public string EMAIL { get; set; }
        public string MOBILE_NO { get; set; }
        public string RELIGION_NAME { get; set; }
        public string STATE_ { get; set; }
        public string LGA { get; set; }
        public string HOME_TOWN { get; set; }
        public string PERMANENT_ADDRESS { get; set; }
        public string BLOODGROUP { get; set; }
        public string PASSPORT_URL { get; set; }
        public string SPONSOR_NAME { get; set; }
        public string SPONSOR_ADDRESS { get; set; }
        public string SPONSOR_PHONE { get; set; }
        public string ENTRY_YEAR { get; set; }
        public string GRADUATION_YEAR { get; set; }
        public string PROGRAMME { get; set; }
        public string LEVEL { get; set; }
    }
}
