//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_MONNIFY_COMMISSION
    {
        public int Id { get; set; }
        public int Fee_Type_Id { get; set; }
        public int Department_Id { get; set; }
        public int Programme_Id { get; set; }
        public int Payment_Mode_Id { get; set; }
        public bool Use_Level { get; set; }
        public Nullable<int> Level_Id { get; set; }
        public decimal Commission { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual FEE_TYPE FEE_TYPE { get; set; }
        public virtual LEVEL LEVEL { get; set; }
        public virtual PAYMENT_MODE PAYMENT_MODE { get; set; }
        public virtual PROGRAMME PROGRAMME { get; set; }
    }
}
