//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_INTERSWITCH
    {
        public long Payment_Interswitch_Id { get; set; }
        public long Payment_Id { get; set; }
        public int Amount { get; set; }
        public string Card_Number { get; set; }
        public string MerchantReference { get; set; }
        public string PaymentReference { get; set; }
        public string RetrievalReferenceNumber { get; set; }
        public string LeadBankCbnCode { get; set; }
        public string LeadBankName { get; set; }
        public string SplitAccounts { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string ResponseCode { get; set; }
        public string ResponseDescription { get; set; }
    
        public virtual PAYMENT PAYMENT { get; set; }
    }
}
