//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_PAYSTACK_COMMISSION_AUDIT
    {
        public int Payment_PayStack_Commission_Audit_Id { get; set; }
        public int FeeType_Id { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> Session_Id { get; set; }
        public long User_Id { get; set; }
        public string Client { get; set; }
        public string Operation { get; set; }
        public string Action { get; set; }
        public System.DateTime Date { get; set; }
        public int Payment_PayStack_Commission_Id { get; set; }
        public Nullable<int> Programme_Id { get; set; }
    
        public virtual FEE_TYPE FEE_TYPE { get; set; }
        public virtual PAYMENT_PAYSTACK_COMMISSION PAYMENT_PAYSTACK_COMMISSION { get; set; }
        public virtual PROGRAMME PROGRAMME { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual USER USER { get; set; }
    }
}
