//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_MONNIFY
    {
        public long Payment_Id { get; set; }
        public string Payment_Method { get; set; }
        public System.DateTime Date_Created { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public bool Invoice_Status { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public string Checkout_Url { get; set; }
        public string Account_Number { get; set; }
        public string Account_Name { get; set; }
        public string Account_Bank_Name { get; set; }
        public string Account_Bank_Code { get; set; }
        public bool Completed { get; set; }
        public Nullable<System.DateTime> Completed_Date { get; set; }
        public string Transaction_Reference { get; set; }
    
        public virtual PAYMENT PAYMENT { get; set; }
    }
}
