//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_MERGER
    {
        public long Person_Merger_Id { get; set; }
        public long Old_Person_Id { get; set; }
        public long New_Person_Id { get; set; }
        public string Description { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        public virtual PERSON PERSON1 { get; set; }
    }
}
