//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCRATCH_CARD_AUDIT
    {
        public long Scratch_Card_Audit_Id { get; set; }
        public long Scratch_Card_Id { get; set; }
        public long Person_Id { get; set; }
        public string Pin { get; set; }
        public string Serial_Number { get; set; }
        public long Old_Person_Id { get; set; }
        public string Operation { get; set; }
        public string Action { get; set; }
        public string Client { get; set; }
        public System.DateTime Time { get; set; }
        public long User_Id { get; set; }
    
        public virtual SCRATCH_CARD SCRATCH_CARD { get; set; }
        public virtual USER USER { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual PERSON PERSON1 { get; set; }
    }
}
