//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCRATCH_CARD_BATCH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCRATCH_CARD_BATCH()
        {
            this.SCRATCH_CARD = new HashSet<SCRATCH_CARD>();
        }
    
        public long Scratch_Card_Batch_Id { get; set; }
        public int Scratch_Card_Type_Id { get; set; }
        public long User_Id { get; set; }
        public System.DateTime Date_Generated { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Expiry_Date { get; set; }
        public byte Usage_Count_Limit { get; set; }
        public decimal Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCRATCH_CARD> SCRATCH_CARD { get; set; }
        public virtual SCRATCH_CARD_TYPE SCRATCH_CARD_TYPE { get; set; }
        public virtual USER USER { get; set; }
    }
}
