//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_QUALIFICATION
    {
        public int Id { get; set; }
        public long Staff_Id { get; set; }
        public string Institution_Attended { get; set; }
        public int Educational_Qualification_Id { get; set; }
        public int Staff_Result_Grade_Id { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string Certificate_Number { get; set; }
    
        public virtual EDUCATIONAL_QUALIFICATION EDUCATIONAL_QUALIFICATION { get; set; }
        public virtual STAFF_RESULT_GRADE STAFF_RESULT_GRADE { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
