//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STAFF()
        {
            this.STAFF_JOB_ROLE = new HashSet<STAFF_JOB_ROLE>();
            this.STAFF_QUALIFICATION = new HashSet<STAFF_QUALIFICATION>();
        }
    
        public long Staff_Id { get; set; }
        public long User_Id { get; set; }
        public Nullable<long> Person_Id { get; set; }
        public int Staff_Type_Id { get; set; }
        public int Department_Id { get; set; }
        public bool IsHead { get; set; }
        public Nullable<bool> Is_Management { get; set; }
        public string Profile_Description { get; set; }
        public Nullable<int> Genotype_Id { get; set; }
        public Nullable<int> Blood_Group_Id { get; set; }
        public Nullable<int> Marital_Status_Id { get; set; }
        public Nullable<int> DepartmentOption_Id { get; set; }
    
        public virtual BLOOD_GROUP BLOOD_GROUP { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual DEPARTMENT_OPTION DEPARTMENT_OPTION { get; set; }
        public virtual EMPLOYEE_DETAIL EMPLOYEE_DETAIL { get; set; }
        public virtual GENOTYPE GENOTYPE { get; set; }
        public virtual MARITAL_STATUS MARITAL_STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STAFF_JOB_ROLE> STAFF_JOB_ROLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STAFF_QUALIFICATION> STAFF_QUALIFICATION { get; set; }
        public virtual STAFF_TYPE STAFF_TYPE { get; set; }
        public virtual USER USER { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
