//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_PAYMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT_PAYMENT()
        {
            this.STUDENT_PAYMENT_AUDIT = new HashSet<STUDENT_PAYMENT_AUDIT>();
        }
    
        public long Payment_Id { get; set; }
        public long Person_Id { get; set; }
        public int Session_Id { get; set; }
        public int Level_Id { get; set; }
        public decimal Amount { get; set; }
        public bool Status { get; set; }
    
        public virtual LEVEL LEVEL { get; set; }
        public virtual PAYMENT PAYMENT { get; set; }
        public virtual SESSION SESSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_PAYMENT_AUDIT> STUDENT_PAYMENT_AUDIT { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
