//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_PAYMENT_AUDIT
    {
        public long Student_Payment_Audit_Id { get; set; }
        public long Payment_Id { get; set; }
        public long Person_Id { get; set; }
        public int Session_Id { get; set; }
        public int Level_Id { get; set; }
        public decimal Amount { get; set; }
        public bool Status { get; set; }
        public long Old_Person_Id { get; set; }
        public int Old_Level_Id { get; set; }
        public int Old_Session_Id { get; set; }
        public decimal Old_Amount { get; set; }
        public bool Old_Status { get; set; }
        public long User_Id { get; set; }
        public string Operation { get; set; }
        public string Action { get; set; }
        public string Client { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual LEVEL LEVEL { get; set; }
        public virtual LEVEL LEVEL1 { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual SESSION SESSION1 { get; set; }
        public virtual STUDENT_PAYMENT STUDENT_PAYMENT { get; set; }
        public virtual USER USER { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual PERSON PERSON1 { get; set; }
    }
}
