//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_COURSE_REGISTRATION_DETAIL_COURSE
    {
        public Nullable<long> Student_Course_Registration_Id { get; set; }
        public long Course_Id { get; set; }
    }
}
