//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSCRIPT_INCIDENT_LOG
    {
        public long Id { get; set; }
        public string Ticket_Id { get; set; }
        public string Description { get; set; }
        public long Transcript_Request_Id { get; set; }
        public bool Status { get; set; }
        public string Email { get; set; }
        public string Phone_No { get; set; }
        public long LoggedBy { get; set; }
        public System.DateTime Date_Opened { get; set; }
        public Nullable<System.DateTime> Date_Closed { get; set; }
        public Nullable<long> ClosedBy { get; set; }
        public int Department_Id { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual TRANSCRIPT_REQUEST TRANSCRIPT_REQUEST { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
