//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_AUDIT
    {
        public long Id { get; set; }
        public long User_Id { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public int Security_Question_Id { get; set; }
        public string Security_Answer { get; set; }
        public int Role_Id { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public Nullable<System.DateTime> LastPasswordChangeDate { get; set; }
        public string Signature_Url { get; set; }
        public string Profile_Image_Url { get; set; }
        public long Action_User_Id { get; set; }
        public string Operation { get; set; }
        public string Action { get; set; }
        public string Client { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual ROLE ROLE { get; set; }
        public virtual SECURITY_QUESTION SECURITY_QUESTION { get; set; }
        public virtual USER USER { get; set; }
    }
}
