//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ADMITTED_STUDENT_DATA
    {
        public long Person_Id { get; set; }
        public string NAME { get; set; }
        public string Local_Government_Name { get; set; }
        public string State_Name { get; set; }
        public string Mobile_Phone { get; set; }
        public string Email { get; set; }
        public string Image_File_Url { get; set; }
        public string Programme_Name { get; set; }
        public int Programme_Id { get; set; }
        public string Department_Name { get; set; }
        public int Department_Id { get; set; }
        public string Sponsor_Name { get; set; }
        public string Relationship_Name { get; set; }
        public string Sponsor_Contact_Address { get; set; }
        public string Sponsor_Mobile_Phone { get; set; }
        public string O_Level_Subject_Name { get; set; }
        public string O_Level_Grade_Name { get; set; }
        public string Session_Name { get; set; }
        public int Session_Id { get; set; }
        public string O_Level_Type_Name { get; set; }
        public string O_Level_Exam_Sitting_Name { get; set; }
        public int O_Level_Exam_Sitting_Id { get; set; }
        public string Exam_Number { get; set; }
        public int Exam_Year { get; set; }
        public Nullable<short> Applicant_Jamb_Score { get; set; }
        public string Applicant_Jamb_Registration_Number { get; set; }
    }
}
