//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ALL_STUDENTS_WITH_JAMB_NUMBER
    {
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Other_Name { get; set; }
        public string Mobile_Phone { get; set; }
        public string Email { get; set; }
        public string Matric_Number { get; set; }
        public string Applicant_Jamb_Registration_Number { get; set; }
        public string Department_Name { get; set; }
        public string Faculty_Name { get; set; }
    }
}
