//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ADMITTED_STUDENT_BREAKDOWN
    {
        public long Admission_List_Id { get; set; }
        public int Department_Id { get; set; }
        public string Department_Name { get; set; }
        public int Programme_Id { get; set; }
        public string Programme_Name { get; set; }
        public int Session_Id { get; set; }
        public string Session_Name { get; set; }
        public string Application_Form_Number { get; set; }
        public long Application_Form_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Other_Name { get; set; }
        public string Admission_List_Type_Name { get; set; }
        public System.DateTime Date_Uploaded { get; set; }
        public string Mobile_Phone { get; set; }
    }
}
