//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_COURSE_REGISTRATION_GST
    {
        public Nullable<long> Student_Number { get; set; }
        public string Matric_Number { get; set; }
        public string Password_hash { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Other_Name { get; set; }
        public string Initial { get; set; }
        public string Title { get; set; }
        public string Image_File_Url { get; set; }
        public string Contact_Address { get; set; }
        public string Email { get; set; }
        public string Mobile_Phone { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public Nullable<int> Religion_Id { get; set; }
        public int Level_Id { get; set; }
        public int Programme_Id { get; set; }
        public int Department_Id { get; set; }
        public int Session_Id { get; set; }
        public Nullable<System.DateTime> Date_Approved { get; set; }
        public long Student_Course_Registration_Detail_Id { get; set; }
        public Nullable<long> Expr3 { get; set; }
        public long Course_Id { get; set; }
        public int Course_Mode_Id { get; set; }
        public Nullable<int> Course_Unit { get; set; }
        public int Semester_Id { get; set; }
        public Nullable<decimal> Test_Score { get; set; }
        public Nullable<decimal> Exam_Score { get; set; }
        public string Special_Case { get; set; }
        public Nullable<System.DateTime> Date_Uploaded { get; set; }
        public string Programme_Name { get; set; }
        public string Programme_Description { get; set; }
        public string Programme_Short_Name { get; set; }
        public string Department_Name { get; set; }
        public string Department_Code { get; set; }
        public int Faculty_Id { get; set; }
        public string Course_Code { get; set; }
        public string Course_Name { get; set; }
        public string Level_Name { get; set; }
        public string Level_Description { get; set; }
        public string Session_Name { get; set; }
        public Nullable<byte> Sex_Id { get; set; }
        public string Sex_Name { get; set; }
    }
}
