//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ETRANZACT_FEETYPE
    {
        public int Fee_Type_Id { get; set; }
        public string Fee_Type_Name { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public string Confirmation_No { get; set; }
    }
}
