//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_GST_YEAR_ONE
    {
        public long Course_Id { get; set; }
        public string Course_Code { get; set; }
        public string Matric_Number { get; set; }
        public string FULLNAME { get; set; }
        public Nullable<decimal> RAW_SCORE { get; set; }
        public Nullable<decimal> CA { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public long Person_Id { get; set; }
        public long Student_Course_Registration_Id { get; set; }
        public Nullable<int> Session_Id { get; set; }
        public Nullable<int> Semester_Id { get; set; }
    }
}
