//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_IAS_APPLICATION_REPORT
    {
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Other_Name { get; set; }
        public string Applicant_Jamb_Registration_Number { get; set; }
        public short Expr1 { get; set; }
        public string State_Name { get; set; }
        public string Local_Government_Name { get; set; }
        public string Mobile_Phone { get; set; }
        public string First_Choice_Course { get; set; }
        public string Qualification_1 { get; set; }
        public string Qualification_2 { get; set; }
        public string Programme_Name { get; set; }
        public int Programme_Id { get; set; }
        public Nullable<short> Applicant_Jamb_Score { get; set; }
    }
}
