//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PAYMENT_PAYSTACK
    {
        public string Expr1 { get; set; }
        public string Matric_NO { get; set; }
        public string Applicant_Jamb_Registration_Number { get; set; }
        public string Level_Name { get; set; }
        public string Department_Name { get; set; }
        public string Faculty_Name { get; set; }
        public string Programme_Name { get; set; }
        public long Payment_Id { get; set; }
        public long Person_Id { get; set; }
        public int Payment_Mode_Id { get; set; }
        public int Payment_Type_Id { get; set; }
        public string Session_Name { get; set; }
        public int Person_Type_Id { get; set; }
        public int Fee_Type_Id { get; set; }
        public Nullable<int> Session_Id { get; set; }
        public Nullable<long> Payment_Serial_Number { get; set; }
        public string Invoice_Number { get; set; }
        public System.DateTime Date_Paid { get; set; }
        public string channel { get; set; }
        public Nullable<System.DateTime> transaction_date { get; set; }
        public string reference { get; set; }
        public string card_type { get; set; }
        public string brand { get; set; }
        public string bank { get; set; }
        public string Fee_Type_Name { get; set; }
        public string Payment_Mode_Name { get; set; }
        public string Payment_Type_Name { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string status { get; set; }
        public string message { get; set; }
        public string domain { get; set; }
    }
}
