//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PGSTUDENT_NOMINAL_REPORT
    {
        public long Person_Id { get; set; }
        public long Expr1 { get; set; }
        public string Name { get; set; }
        public string Matric_No { get; set; }
        public string Programme_Name { get; set; }
        public string Department_Name { get; set; }
        public int Department_Id { get; set; }
        public int Programme_Id { get; set; }
        public long Expr2 { get; set; }
        public Nullable<int> Local_Government_Id { get; set; }
        public string Local_Government_Name { get; set; }
        public string State_Id { get; set; }
        public string State_Name { get; set; }
        public int GeneratedLevelId { get; set; }
        public string GeneratedLevel { get; set; }
    }
}
