//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PROCESSED_SUPPLEMENTARY_REPORT
    {
        public long Person_Id { get; set; }
        public string Name { get; set; }
        public string JambRegNumber { get; set; }
        public Nullable<decimal> COMPUTED_JAMB_SCORE { get; set; }
        public short Applicant_Jamb_Score { get; set; }
        public Nullable<double> RAW_SCORE { get; set; }
        public Nullable<double> COMPUTED_PUTME_SCORE { get; set; }
        public Nullable<double> SUM { get; set; }
        public string State_Name { get; set; }
        public string Local_Government_Name { get; set; }
        public string Mobile_Phone { get; set; }
        public string Sex_Name { get; set; }
        public string Institution_Choice_Name { get; set; }
        public int Institution_Choice_Id { get; set; }
        public int FirstChoiceCourseId { get; set; }
        public string FirstChoiceCourse { get; set; }
        public int SupplementaryCourseId { get; set; }
        public string SupplementaryCourse { get; set; }
        public int Session_Id { get; set; }
        public string Session_Name { get; set; }
        public int Application_Form_Setting_Id { get; set; }
        public string Application_Form_Setting_Name { get; set; }
        public string Qualification1 { get; set; }
        public string Qualification2 { get; set; }
    }
}
