//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_STUDENT_BIODATA
    {
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public int Person_Type_Id { get; set; }
        public string Other_Name { get; set; }
        public string Initial { get; set; }
        public string Title { get; set; }
        public string Image_File_Url { get; set; }
        public string Signature_File_Url { get; set; }
        public Nullable<byte> Sex_Id { get; set; }
        public string Home_address_detail { get; set; }
        public string Email { get; set; }
        public string Mobile_Phone { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string State_Id { get; set; }
        public Nullable<int> Local_Government_Id { get; set; }
        public string Home_Town { get; set; }
        public string Home_Address { get; set; }
        public int Nationality_Id { get; set; }
        public Nullable<int> Religion_Id { get; set; }
        public System.DateTime Date_Entered { get; set; }
        public int Role_Id { get; set; }
        public string State_Name { get; set; }
        public string Nationality_Name { get; set; }
        public string Local_Government_Name { get; set; }
        public string RegistrationNumber { get; set; }
        public int Programme_Id { get; set; }
        public int Level_Id { get; set; }
        public string Programme_Name { get; set; }
        public string Programme_Short_Name { get; set; }
        public string Applicant_Jamb_Registration_Number { get; set; }
        public Nullable<short> Applicant_Jamb_Score { get; set; }
        public string Department_Name { get; set; }
        public string Department_Code { get; set; }
        public string Faculty_Name { get; set; }
        public string Genotype_Name { get; set; }
        public string Blood_Group_Name { get; set; }
        public string Title_Name { get; set; }
        public string Marital_Status_Name { get; set; }
        public string Religion_Name { get; set; }
        public string Sponsor_Name { get; set; }
        public string Sponsor_Contact_Address { get; set; }
        public string Sponsor_Mobile_Phone { get; set; }
        public string Sponor_Email { get; set; }
        public int Sponsor_Relationship { get; set; }
        public string Sex_Name { get; set; }
        public string Next_of_Kin_Name { get; set; }
        public string Next_of_Kin_Address { get; set; }
        public string Next_of_Kin_Mobile { get; set; }
        public int Next_Of_kin_Relationship { get; set; }
        public long Person_Id { get; set; }
        public Nullable<long> Application_Form_Id { get; set; }
        public int Student_Type_Id { get; set; }
        public int Student_Category_Id { get; set; }
        public int Student_Status_Id { get; set; }
        public Nullable<long> Student_Number { get; set; }
        public string Matric_Number { get; set; }
        public Nullable<int> Title_Id { get; set; }
        public Nullable<int> Marital_Status_Id { get; set; }
        public Nullable<int> Blood_Group_Id { get; set; }
        public Nullable<int> Genotype_Id { get; set; }
        public string School_Contact_Address { get; set; }
        public Nullable<bool> Activated { get; set; }
        public string Reason { get; set; }
        public string Reject_Category { get; set; }
        public string Password_hash { get; set; }
        public long Admission_List_Id { get; set; }
        public int Admission_List_Batch_Id { get; set; }
        public int Department_Id { get; set; }
        public Nullable<int> Department_Option_Id { get; set; }
        public Nullable<int> Institution_Choice_Id { get; set; }
        public Nullable<int> Subject1 { get; set; }
        public Nullable<int> Subject2 { get; set; }
        public Nullable<int> Subject3 { get; set; }
        public Nullable<int> Subject4 { get; set; }
        public int Faculty_Id { get; set; }
        public string FULLNAME { get; set; }
        public string Contact_Address { get; set; }
        public long Expr1 { get; set; }
        public Nullable<int> Year_Of_Graduation { get; set; }
    }
}
