//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_STUDENT_ID_DATA
    {
        public long Person_Id { get; set; }
        public string FULL_NAME { get; set; }
        public string IMAGE_URL { get; set; }
        public string BLOOD_GROUP { get; set; }
        public string Matric_Number { get; set; }
        public int Department_Id { get; set; }
        public string DEPARTMENT { get; set; }
        public int Programme_Id { get; set; }
        public string PROGRAMME { get; set; }
        public int Session_Id { get; set; }
        public string SESSION { get; set; }
        public int Year_Of_Admission { get; set; }
        public int Year_Of_Graduation { get; set; }
        public string Application_Form_Number { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public Nullable<System.DateTime> Date_Entered { get; set; }
    }
}
