//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_STDUENT_DETAILS
    {
        public long Person_Id { get; set; }
        public string NAME { get; set; }
        public string Sex_Name { get; set; }
        public string Application_Exam_Number { get; set; }
        public string Application_Form_Number { get; set; }
        public string Matric_Number { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public string Department_Name { get; set; }
        public int Level_Id { get; set; }
        public string Level_Name { get; set; }
        public string Programme_Name { get; set; }
        public Nullable<int> Programme_Id { get; set; }
        public string Mobile_Phone { get; set; }
        public Nullable<System.DateTime> Date_Submitted { get; set; }
        public Nullable<System.DateTime> Exam_Date { get; set; }
        public int Session_Id { get; set; }
        public string Session_Name { get; set; }
    }
}
