//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_TRANSCRIPT_REQUEST_BY_INTERSWITCH
    {
        public long Transcript_Request_Id { get; set; }
        public Nullable<long> Payment_Id { get; set; }
        public Nullable<long> Student_id { get; set; }
        public string NAME { get; set; }
        public string RegNo { get; set; }
        public string Email { get; set; }
        public string Department_Name { get; set; }
        public int Department_Id { get; set; }
        public int Programme_Id { get; set; }
        public int Level_Id { get; set; }
        public int Faculty_Id { get; set; }
        public System.DateTime Date_Requested { get; set; }
        public string Destination_Address { get; set; }
        public string Destination_State_Id { get; set; }
        public string Destination_Country_Id { get; set; }
        public Nullable<int> Transcript_clearance_Status_Id { get; set; }
        public int Transcript_Status_Id { get; set; }
        public string Transcript_Status_Name { get; set; }
        public string Delivery_Zone { get; set; }
        public string Delivery_Service { get; set; }
    }
}
