//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_UNDERGRADUATE_NOMINAL_REPORT
    {
        public Nullable<long> Person_Id { get; set; }
        public string Name { get; set; }
        public string Matric_Number { get; set; }
        public string Programme_Name { get; set; }
        public string Department_Name { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public Nullable<int> Programme_Id { get; set; }
        public Nullable<int> Level_Id { get; set; }
        public string Level_Name { get; set; }
        public Nullable<long> Expr1 { get; set; }
        public Nullable<int> Expr2 { get; set; }
        public Nullable<int> Local_Government_Id { get; set; }
        public string Local_Government_Name { get; set; }
        public Nullable<int> Duration { get; set; }
        public int CalculatedLevelId { get; set; }
        public string CalculatedLevelName { get; set; }
        public Nullable<int> Department_Option_Id { get; set; }
        public string State_Id { get; set; }
        public string State_Name { get; set; }
    }
}
